#!/usr/bin/env bash
#Bash script that pings an ip address passed as argument


#extract the ip address
ip_address=$1

if [ $# -eq 0 ]
	then
		echo "usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
		
	else
		ping -c 5 "$ip_address"
fi



