#!/usr/bin/env bash
#Bash script that pings an ip address passed as argument


#extract the ip address
iip_address=$1

if [ $# -eq 0 ]
	then
		echo "usage: $0 {IP_ADDRESS}"
		
	else
		ping -c 5 "$ip_address"
fi



